name: Prepare Daily Folio

on:
  workflow_dispatch: # Allows manual running
  schedule:
    # Runs at 08:00 UTC every day (4 AM ADT / 3 AM EST)
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: The Scribe prepares the Daily Folio
        run: python scribe.py

      - name: Commit and push the Daily Folio
        run: |
          git config --global user.name "The Digital Scribe"
          git config --global user.email "actions@github.com"
          git add daily_folio.json
          git diff --staged --quiet || git commit -m "Prepare Folio for $(date -u +'%B %d, %Y')"
          git push